export const GET_TRAINERS = 'GET_TRAINERS';
export const GET_PACKAGES = 'GET_PACKAGES';
export const GET_THREETRANSFORMATIONS = 'GET_THREETRANSFORMATIONS';
export const GET_ALL_TRANSFORMATIONS = 'GET_ALL_TRANSFORMATIONS';
export const ADD_EVENT_TO_PLAN = 'ADD_EVENT_TO_PLAN';
